version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/cd-demo/
permissions:
  - object: /home/ubuntu/cd-demo
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/install_dependancies.sh
      timeout: 6000
      runas: ubuntu
  AfterInstall:
    - location: scripts/gunicorn.sh
      timeout: 600
      runas: ubuntu
    - location: scripts/ngnix.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 600
      runas: ubuntu

